#
# FS Loox Makefile for the linux kernel.
#
obj-$(CONFIG_MACH_LOOX720)	+= loox720.o
obj-$(CONFIG_MACH_LOOX720)	+= loox720_core.o
obj-$(CONFIG_MACH_LOOX720)	+= loox720_cpld.o
obj-$(CONFIG_MACH_LOOX720)	+= loox720_leds.o
obj-$(CONFIG_MACH_LOOX720)	+= loox720_battery.o
#obj-$(CONFIG_LOOX720_CORE)	+= loox720_core.o
obj-$(CONFIG_LOOX720_LCD)	+= loox720_lcd.o
obj-$(CONFIG_LOOX720_TS)        += loox720_ts.o
obj-$(CONFIG_LOOX720_BUTTONS)	+= loox720_buttons.o
obj-$(CONFIG_LOOX720_BT)	+= loox720_bt.o
obj-$(CONFIG_MACH_LOOX720)	+= gpioed-ng.o
obj-$(CONFIG_LOOX720_CPLD_EDIT)	+= cpld_edit.o
obj-$(CONFIG_LOOX720_PCMCIA)	+= loox720_pcmcia.o
obj-$(CONFIG_LOOX720_WIFI)		+= loox720_acx.o

#obj-m				+= loox720_test.o
