#
# Dell Axim PDA Makefile for the linux kernel.
#
#obj-$(CONFIG_MACH_X30)         += aximx30_core_minimal.o
obj-$(CONFIG_MACH_LOOX720)	+= loox720.o 
obj-$(CONFIG_MACH_LOOX720)	+= loox720_core.o
obj-$(CONFIG_MACH_LOOX720)	+= loox720_battery.o 
#obj-$(CONFIG_LOOX720_CORE)	+= loox720_core.o
obj-$(CONFIG_LOOX720_LCD)	+= loox720_lcd.o
obj-$(CONFIG_LOOX720_TS)       += loox720_ts.o
obj-$(CONFIG_LOOX720_BUTTONS)	+= loox720_buttons.o
obj-$(CONFIG_MACH_LOOX720)	+= gpioed-ng.o
 
